export const INIT_APP = 'INIT_APP';
export const GET_CURRENT_NETWORK = 'GET_CURRENT_NETWORK';
export const GET_USD_PRICE = 'GET_USD_PRICE';

export const BIRTH = 'BIRTH';

export const LOAD_ACCOUNT_CARDS = 'LOAD_ACCOUNT_CARDS';
export const LOAD_CARDS = 'LOAD_CARDS';

export const WATCH_TRANSFERS = 'WATCH_TRANSFERS';

export const LOAD_BENEFACTORS = 'LOAD_BENEFACTORS';
