export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_CURRENT_NETWORK = "SET_CURRENT_NETWORK";
export const SET_ETHERSCAN_NETWORK = "SET_ETHERSCAN_NETWORK";
export const SET_USD_PRICE = "SET_USD_PRICE";
export const SET_WEB3 = "SET_WEB3";

export const SET_UPLOAD_HASH = "SET_UPLOAD_HASH";
export const SET_ACCOUNT_CARDS = "SET_ACCOUNT_CARDS";
export const SET_CARDS = "SET_CARDS";

export const SET_DEEP_URL_CARD = "SET_DEEP_URL_CARD";

export const SET_DEEP_URL_CARD_NUMBER = "SET_DEEP_URL_CARD_NUMBER";

export const SET_TOTAL_SUPPLY = "SET_TOTAL_SUPPLY";

export const SET_TRANSFER = "SET_TRANSFER";
export const SET_TRANSFER_STATUS = "SET_TRANSFER_STATUS";
export const CLEAR_TRANSFER_STATUS = "CLEAR_TRANSFER_STATUS";

export const SET_GIFT_STATUS = "SET_GIFT_STATUS";
export const CLEAR_GIFT_STATUS = "CLEAR_GIFT_STATUS";

export const SET_BENEFACTORS = "SET_BENEFACTORS";
