export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_CURRENT_NETWORK = "SET_CURRENT_NETWORK";
export const SET_ETHERSCAN_NETWORK = "SET_ETHERSCAN_NETWORK";
export const SET_WEB3 = "SET_WEB3";
export const SET_PORTIS_SIGNED_IN = "SET_PORTIS_SIGNED_IN";

export const SET_UPLOAD_HASH = "SET_UPLOAD_HASH";
export const SET_ACCOUNT_CARDS = "SET_ACCOUNT_CARDS";
export const PUSH_ACCOUNT_CARD = "PUSH_ACCOUNT_CARD";
export const SET_CARDS = "SET_CARDS";

export const SET_DEEP_URL_CARD = "SET_DEEP_URL_CARD";

export const SET_DEEP_URL_CARD_NUMBER = "SET_DEEP_URL_CARD_NUMBER";

export const SET_TOTAL_SUPPLY = "SET_TOTAL_SUPPLY";
export const SET_USD_PRICE = "SET_USD_PRICE";
export const SET_CYN_PRICE = "SET_CYN_PRICE";
export const SET_TOTAL_DONATED_IN_ETH = "SET_TOTAL_DONATED_IN_ETH";
export const SET_TOTAL_DONATED_IN_DAI = "SET_TOTAL_DONATED_IN_DAI";
export const SET_TOTAL_GIFTED_IN_ETH = "SET_TOTAL_GIFTED_IN_ETH";
export const SET_TOTAL_GIFTED_IN_DAI = "SET_TOTAL_GIFTED_IN_DAI";

export const SET_EPHEMERAL_ADDRESS_FEE = "SET_EPHEMERAL_ADDRESS_FEE"
export const SET_EPHEMERAL_PRIVATE_KEY = "SET_EPHEMERAL_PRIVATE_KEY";
export const ADD_EPHEMERAL_WALLET = "ADD_EPHEMERAL_WALLET";

export const SET_ACCOUNT_ETH_BALANCE = "SET_ACCOUNT_ETH_BALANCE";
export const SET_ACCOUNT_DAI_BALANCE = "SET_ACCOUNT_DAI_BALANCE";
export const SET_ACCOUNT_DAI_ALLOWANCE = "SET_ACCOUNT_DAI_ALLOWANCE";
export const SET_DAI_CONTRACT_ADDRESS = "SET_DAI_CONTRACT_ADDRESS";

export const SET_TRANSFER = "SET_TRANSFER";
export const SET_TRANSFER_STATUS = "SET_TRANSFER_STATUS";
export const CLEAR_TRANSFER_STATUS = "CLEAR_TRANSFER_STATUS";

export const SET_GIFT_STATUS = "SET_GIFT_STATUS";
export const CLEAR_GIFT_STATUS = "CLEAR_GIFT_STATUS";

export const SET_BENEFACTORS = "SET_BENEFACTORS";
